// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxgezciuuacdlyvsvgev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Z2V6Y2l1dWFjZGx5dnN2Z2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDQ4MjQsImV4cCI6MjA3MTEyMDgyNH0.oeD9ibftRkxzmzdeTpPUe_HgsEK9aa_0eBWB90_dxu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});